
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'INCLUDE INT IOSTREAM LBRACE LPAREN MAIN OUTPUT_OPERATOR RBRACE RETURN RPAREN SEMICOLON STD_COUT STD_ENDL STRING ZEROprogram : include_directive main_functioninclude_directive : INCLUDE IOSTREAMmain_function : INT MAIN LPAREN RPAREN LBRACE statements RBRACEstatements : statement statement\n                  | emptystatement : output_statement\n                 | return_statementoutput_statement : STD_COUT OUTPUT_OPERATOR STRING OUTPUT_OPERATOR STD_ENDL SEMICOLONreturn_statement : RETURN ZERO SEMICOLONempty : '
    
_lr_action_items = {'INCLUDE':([0,],[3,]),'$end':([1,4,18,],[0,-1,-3,]),'INT':([2,6,],[5,-2,]),'IOSTREAM':([3,],[6,]),'MAIN':([5,],[7,]),'LPAREN':([7,],[8,]),'RPAREN':([8,],[9,]),'LBRACE':([9,],[10,]),'RBRACE':([10,11,13,14,15,19,23,26,],[-10,18,-5,-6,-7,-4,-9,-8,]),'STD_COUT':([10,12,14,15,23,26,],[16,16,-6,-7,-9,-8,]),'RETURN':([10,12,14,15,23,26,],[17,17,-6,-7,-9,-8,]),'OUTPUT_OPERATOR':([16,22,],[20,24,]),'ZERO':([17,],[21,]),'STRING':([20,],[22,]),'SEMICOLON':([21,25,],[23,26,]),'STD_ENDL':([24,],[25,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'include_directive':([0,],[2,]),'main_function':([2,],[4,]),'statements':([10,],[11,]),'statement':([10,12,],[12,19,]),'empty':([10,],[13,]),'output_statement':([10,12,],[14,14,]),'return_statement':([10,12,],[15,15,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> include_directive main_function','program',2,'p_program','Lab3.py',57),
  ('include_directive -> INCLUDE IOSTREAM','include_directive',2,'p_include_directive','Lab3.py',61),
  ('main_function -> INT MAIN LPAREN RPAREN LBRACE statements RBRACE','main_function',7,'p_main_function','Lab3.py',65),
  ('statements -> statement statement','statements',2,'p_statements','Lab3.py',69),
  ('statements -> empty','statements',1,'p_statements','Lab3.py',70),
  ('statement -> output_statement','statement',1,'p_statement','Lab3.py',77),
  ('statement -> return_statement','statement',1,'p_statement','Lab3.py',78),
  ('output_statement -> STD_COUT OUTPUT_OPERATOR STRING OUTPUT_OPERATOR STD_ENDL SEMICOLON','output_statement',6,'p_output_statement','Lab3.py',82),
  ('return_statement -> RETURN ZERO SEMICOLON','return_statement',3,'p_return_statement','Lab3.py',86),
  ('empty -> <empty>','empty',0,'p_empty','Lab3.py',90),
]
